### ISSUE TITLE
another way to spot a windows event log clear

### ISSUE THREAD

**Issue by Th4nat0s** [fr0gger/Unprotect_Submission#12]
on  https://unprotect.it/technique/clear-windows-event-logs/ 

It's foundable also by looking at event clear id 1102 ( event when audit log is cleared )
https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-1102)

**Comment by fr0gger** [comment]
Thank you, updated here: https://unprotect.it/technique/clear-windows-event-logs/
